### PR TITLE
Systemctl Daemon

### PR DESCRIPTION
**Pull request by trojanz07**

### CODE REVIEW

**Comment by Hye-Dev** [comment]
Ararat is cross-platform with Windows, macOS, and Linux. Systemctl is not compatible with macOS and Windows, therefor this would break that cross-platform functionality. Can you modify the script to only add the daemon if it is on a Linux host?

**Review by Hye-Dev — CHANGES_REQUESTED** [review]
Please update based on the comments above

**Comment by trojanz07** [comment]
Okay, give me couple of hours.

**Comment by trojanz07** [comment]
`#!/bin/bash
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if [ "$EUID" -ne 0 ]
                then echo "Please run as root"
                exit
        fi


        apt install curl
        curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
        apt install -y nodejs git
        content=`wget https://raw.githubusercontent.com/Hye-Ararat/Ararat/main/ararat.service`

        mv ./ararat.service /lib/systemd/system/ararat.service

        mkdir /etc/ararat && cd /etc/ararat

        git clone https://github.com/Hye-Ararat/Ararat .

        echo "What is your postgres url:" 
        read postgres
        echo "DATABASE_URL=$postgres" | tee .env

        echo "What is your encryption key:" 
        read enc_key
        echo "What is your panel url:"
        read panel
        echo -e "ENC_KEY=$enc_key 
        PANEL_URL=$panel" | tee .env.local


        npm install

        systemctl enable --now ararat

        printf "Thank for installing Ararat ;)"

elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Mac OS"
elif [[ "$OSTYPE" == "msys" ]]; then
        echo "Windows"
else
        echo "No compatible OS"
fi`

It needs to be checked also in  darwin and msys, how do you want to fill that out?

**Review by Hye-Dev — CHANGES_REQUESTED** [review]
As seen in `configure.js`, a lot of the setup in this is already pre done and is not necessary. Please remove the irrelevant setup. Also please use NVM to install node and node node source, that way it can automatically use the LTS release and can be easy to update.

**Comment by Hye-Dev** [comment]
In Ararat v2.0.0 Alpha 1 we have fundamentally changed the way that Ararat starts. We integrated a new systemctl service in Ararat with this new build, therefor this is out of date and no longer required.

**Pull request closed without merging**
