### PR TITLE
Added logo and updated readme

### PR DESCRIPTION
**Pull request by rawbyt3s**

### CODE REVIEW

**Comment by Hye-Dev** [comment]
Hey Rawbytes,

In the task I meant adding the logo to the navigation bar, the login page, etc. but the readme change is also welcome! Please add that to those as well and I will accept your PR.

**Comment by rawbyt3s** [comment]
update with logo on homepage

**Comment by Hye-Dev** [comment]
Hey Rawbytes,

Can you remove the text that says "Hye Ararat" at the top and make the logo a bit smaller. Also please add the logo to the login page.

Great work! - Joseph

**Comment by rawbyt3s** [comment]
Okay. I think I got it this time.

**Comment by Hye-Dev** [comment]
Hey Rawbytes,

Can you center the logo on the login page?

Thanks

**Pull request merged**
